env:
  es6: true
  node: true
  browser: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  prettier/prettier: error
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    -
      avoidEscape: true
  semi:
    - error
    - always
  eol-last:
    - error
  no-trailing-spaces:
    - error
  no-multi-spaces:
    - error
  template-curly-spacing:
    - error
  no-console:
    - off
  no-var:
    - error
  prefer-const:
    - error
  prefer-rest-params:
    - warn
  prefer-spread:
    - warn
  prefer-template:
    - warn
